In [2]:
import numpy as np
def pca_2d(data):
    """
    Perform PCA on 2D data (two features x and y).
    data: numpy array of shape (n_samples, 2)
    """

    # 1. Standardize: subtract mean
    mean_vector = np.mean(data, axis=0)
    data_centered = data - mean_vector

    # 2. Compute covariance matrix
    cov_matrix = np.cov(data_centered.T)

    # 3. Eigen decomposition
    eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

    # 4. Sort eigenvalues (descending)
    idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[idx]
    eigenvectors = eigenvectors[:, idx]

    # 5. Project data onto principal components
    projected_data = data_centered @ eigenvectors

    return {
        "mean_vector": mean_vector,
        "covariance_matrix": cov_matrix,
        "eigenvalues": eigenvalues,
        "eigenvectors": eigenvectors,
        "projected_data": projected_data
    }

if __name__ == "__main__":
    data = np.array([
        [2.5, 2.4],
        [0.5, 0.7],
        [2.2, 2.9],
        [1.9, 2.2],
        [3.1, 3.0],
        [2.3, 2.7],
        [2.0, 1.6],
        [1.0, 1.1],
        [1.5, 1.6],
        [1.1, 0.9]
    ])

    result = pca_2d(data)

    print("\nMean Vector:\n", result["mean_vector"])
    print("\nCovariance Matrix:\n", result["covariance_matrix"])
    print("\nEigenvalues:\n", result["eigenvalues"])
    print("\nEigenvectors (Principal Directions):\n", result["eigenvectors"])
    print("\nProjected Data (PCA Coordinates):\n", result["projected_data"])



Mean Vector:
 [1.81 1.91]

Covariance Matrix:
 [[0.61655556 0.61544444]
 [0.61544444 0.71655556]]

Eigenvalues:
 [1.28402771 0.0490834 ]

Eigenvectors (Principal Directions):
 [[-0.6778734  -0.73517866]
 [-0.73517866  0.6778734 ]]

Projected Data (PCA Coordinates):
 [[-0.82797019 -0.17511531]
 [ 1.77758033  0.14285723]
 [-0.99219749  0.38437499]
 [-0.27421042  0.13041721]
 [-1.67580142 -0.20949846]
 [-0.9129491   0.17528244]
 [ 0.09910944 -0.3498247 ]
 [ 1.14457216  0.04641726]
 [ 0.43804614  0.01776463]
 [ 1.22382056 -0.16267529]]
